open_screen: 
  keys: 
    - key.keyboard.i
    - key.keyboard.g
gui: 
  theme: 
    light_mode: false
    color_scheme_seeds: 
      - "#445E9E"
      - "#6B4EC8"
      - "#2E7D32"
      - "#D2703B"
      - "#C2185B"
      - "#8647B3"
    color_scheme_seed: "#C2185B"
  screen: 
    fade_in_offset: 0.1
    fade_in_duration: "150ms"
    pause_game: false
  toast: 
    adaptive_color_scheme: true
    light_mode: true
    offset: 
      x: 0.5
      y: 0.85
  scroller: 
    scroll_multiplier_1: 2.5
    scroll_multiplier_1_key_code: key.keyboard.left.shift
    scroll_multiplier_2: 5.0
    scroll_multiplier_2_key_code: key.keyboard.left.control
    scroll_multiplier_3: 10.0
    scroll_multiplier_3_key_code: key.keyboard.left.alt
