open_screen: 
  keys: 
    - key.keyboard.h
    - key.keyboard.s
tutorial_step: NONE
pick_player_head_on_creative: false
render_info_addon: 
  use_iris_compatible_pipeline: 
    keybind: 
      keys: []
    enabled: false
  always_render_barrier: 
    keybind: 
      keys: []
    enabled: false
  always_render_light: 
    keybind: 
      keys: []
    enabled: false
  disable_text_obfuscation_render: false
  disable_scoreboard_sidebar_render: 
    keybind: 
      keys: []
    enabled: false
  gamma_override: 
    enable: 
      keybind: 
        keys: []
      enabled: false
    gamma: 1.0
  tnt: 
    tnt_fuse: None
    only_y_rotation: false
    use_max_light: true
  creeper: 
    fuse: None
    only_y_rotation: false
    use_max_light: true
  held_item: 
    enable: 
      keybind: 
        keys: []
      enabled: false
    offset: 
      x: 0.0
      y: 0.0
    spacing: 1.0
    shadow: true
    text_background: "#00000000"
    overall_background: "#00000000"
    item_stack_info: 
      script: |
        //example
        //if(itemStack.getCount()<16){
        //  renderState["count"] = false;
        //}
      name: true
      count: true
      damage: false
      item_id: false
      component_count: false
      tooltip_display: true
      tropical_fish/pattern: false
      instrument: false
      map_id: false
      bees: false
      container_loot: false
      container: false
      banner_patterns: false
      pot_decorations: false
      written_book_content: false
      charged_projectiles: false
      fireworks: false
      firework_explosion: false
      potion_contents: false
      jukebox_playable: false
      trim: false
      stored_enchantments: false
      enchantments: false
      dyed_color: false
      profile: false
      lore: false
      attribute_modifiers: false
      unbreakable: false
      ominous_bottle_amplifier: false
      suspicious_stew_effects: false
      block_state: false
      entity_data: false
      block_entity_data: false
      can_break: false
      can_place_on: false
      disabled_item_tooltip: false
      op_nbt_warning: false
  drop_entity: 
    enable: 
      keybind: 
        keys: []
      enabled: false
    distance: 233.0
    use_max_light: false
    offset: 
      x: 0.0
      y: 0.0
      z: 0.0
    spacing: 0.0
    default_color: "#FFFFFF"
    background_color: "#66000000"
    invert_outline_color: false
    text_outline_color: "#00000000"
    display_mode: NORMAL
    only_y_rotation: false
    experience_orb_value: 
      keybind: 
        keys: []
      enabled: false
    item_stack_info: 
      script: |
        //example
        //if(itemStack.getCount()<16){
        //  renderState["count"] = false;
        //}
      name: true
      count: true
      damage: false
      item_id: false
      component_count: false
      tooltip_display: true
      tropical_fish/pattern: false
      instrument: false
      map_id: false
      bees: false
      container_loot: false
      container: false
      banner_patterns: false
      pot_decorations: false
      written_book_content: false
      charged_projectiles: false
      fireworks: false
      firework_explosion: false
      potion_contents: false
      jukebox_playable: false
      trim: false
      stored_enchantments: false
      enchantments: false
      dyed_color: false
      profile: false
      lore: false
      attribute_modifiers: false
      unbreakable: false
      ominous_bottle_amplifier: false
      suspicious_stew_effects: false
      block_state: false
      entity_data: false
      block_entity_data: false
      can_break: false
      can_place_on: false
      disabled_item_tooltip: false
      op_nbt_warning: false
gameplay: 
  auto_rebirth: 
    keybind: 
      keys: []
    enabled: false
  chain_doors: 
    enable: 
      keybind: 
        keys: []
      enabled: false
    activation_key: key.keyboard.left.shift
    rules: 
      - 
        origin_door: 
          mode: AllMatch
          entries: 
            - 
              type: tag
              mode: Include
              tag: "minecraft:mob_interactable_doors"
        chain_door: 
          mode: AllMatch
          entries: 
            - 
              type: tag
              mode: Include
              tag: "minecraft:mob_interactable_doors"
        key_toggle_mode: false
        strategy: 
          type: neighborhood
          radius: 1
          shape: CUBE
          same_block: true
          sync_state: true
          limit: 1
      - 
        origin_door: 
          mode: AllMatch
          entries: 
            - 
              type: tag
              mode: Include
              tag: "minecraft:trapdoors"
            - 
              type: block
              mode: Exclude
              block: "minecraft:iron_trapdoor"
        chain_door: 
          mode: AllMatch
          entries: 
            - 
              type: tag
              mode: Include
              tag: "minecraft:trapdoors"
            - 
              type: block
              mode: Exclude
              block: "minecraft:iron_trapdoor"
        key_toggle_mode: true
        strategy: 
          type: recursive
          same_block: true
          sync_state: true
          limit: 8
  item_use_intercept: 
    enable: 
      keybind: 
        keys: []
      enabled: false
    matcher: {}
  item_drop_intercept: 
    enable: 
      keybind: 
        keys: []
      enabled: false
    matcher: {}
  block_break_protection: 
    enable: 
      keybind: 
        keys: []
      enabled: false
    matcher: 
      "Budding Amethyst": 
        first: 
          mode: AnyMatch
          entries: 
            - 
              type: item
              mode: Include
              item: "minecraft:air"
            - 
              type: item
              mode: Exclude
              item: "minecraft:air"
        second: 
          mode: AnyMatch
          entries: 
            - 
              type: block
              mode: Include
              block: "minecraft:budding_amethyst"
  gliding: 
    disable_firework_rocket_interaction_when_gliding: 
      keybind: 
        keys: []
      enabled: false
    quick_use_firework_rocket__when_gliding: 
      keys: []
    firework_matcher: 
      mode: AnyMatch
      entries: 
        - 
          type: item
          mode: Include
          item: "minecraft:firework_rocket"
  auto_switch_elytra: 
    enable: 
      keybind: 
        keys: []
      enabled: false
    slot: CHEST
    switchable_equip: 
      mode: AnyMatch
      entries: 
        - 
          type: item
          mode: Include
          item: "minecraft:netherite_chestplate"
        - 
          type: item
          mode: Include
          item: "minecraft:diamond_chestplate"
        - 
          type: item
          mode: Include
          item: "minecraft:chainmail_chestplate"
        - 
          type: item
          mode: Include
          item: "minecraft:iron_chestplate"
        - 
          type: item
          mode: Include
          item: "minecraft:leather_chestplate"
        - 
          type: item
          mode: Include
          item: "minecraft:golden_chestplate"
    switchable_glider: 
      mode: AnyMatch
      entries: 
        - 
          type: item
          mode: Include
          item: "minecraft:elytra"
  auto_replant: 
    enable: 
      keybind: 
        keys: []
      enabled: false
    mapping: 
      - 
        target_block: 
          mode: AllMatch
          entries: 
            - 
              type: block
              mode: Include
              block: "minecraft:wheat"
        replant_item: 
          mode: AllMatch
          entries: 
            - 
              type: item
              mode: Include
              item: "minecraft:wheat_seeds"
        ground_block: 
          mode: AllMatch
          entries: 
            - 
              type: block
              mode: Include
              block: "minecraft:farmland"
      - 
        target_block: 
          mode: AllMatch
          entries: 
            - 
              type: block
              mode: Include
              block: "minecraft:carrots"
        replant_item: 
          mode: AllMatch
          entries: 
            - 
              type: item
              mode: Include
              item: "minecraft:carrot"
        ground_block: 
          mode: AllMatch
          entries: 
            - 
              type: block
              mode: Include
              block: "minecraft:farmland"
      - 
        target_block: 
          mode: AllMatch
          entries: 
            - 
              type: block
              mode: Include
              block: "minecraft:potatoes"
        replant_item: 
          mode: AllMatch
          entries: 
            - 
              type: item
              mode: Include
              item: "minecraft:potato"
        ground_block: 
          mode: AllMatch
          entries: 
            - 
              type: block
              mode: Include
              block: "minecraft:farmland"
      - 
        target_block: 
          mode: AllMatch
          entries: 
            - 
              type: block
              mode: Include
              block: "minecraft:beetroots"
        replant_item: 
          mode: AllMatch
          entries: 
            - 
              type: item
              mode: Include
              item: "minecraft:beetroot_seeds"
        ground_block: 
          mode: AllMatch
          entries: 
            - 
              type: block
              mode: Include
              block: "minecraft:farmland"
      - 
        target_block: 
          mode: AllMatch
          entries: 
            - 
              type: block
              mode: Include
              block: "minecraft:nether_wart"
        replant_item: 
          mode: AllMatch
          entries: 
            - 
              type: item
              mode: Include
              item: "minecraft:nether_wart"
        ground_block: 
          mode: AllMatch
          entries: 
            - 
              type: block
              mode: Include
              block: "minecraft:soul_sand"
  camera_switcher: 
    shortcut_key: 
      keys: []
    block_player_actions: false
  sound_event_filter: 
    enable: 
      keybind: 
        keys: []
      enabled: false
    filter_mapping: []
chat: 
  chat_inject: 
    enable: 
      keybind: 
        keys: []
      enabled: false
    inject_mapping: 
      - 
        first: ".*"
        second: "#{message}"
  chat_filter: 
    enable: 
      keybind: 
        keys: []
      enabled: false
    filter_mapping: []
  chat_bubble: 
    enable: false
    only_y_rotation: true
    offset: 
      x: 0.0
      y: 0.0
    scale: 
      x: 1.0
      y: 1.0
    use_max_light: false
    max_width: 120.0
    texture_color: "#FF8899"
    text_color: "#FFFFFF"
    duration: "10s"
    fade_in_duration: "250ms"
    fade_out_duration: "250ms"
    server_chat_bubble_config: 
      "#single": 
        regex: "<(?<name>[^>]+)>\\s(?<message>.+)"
        enable_uuid: false
        enable_profile: false
